CREATE DATABASE MEDICALINSURANCE
USE MEDICALINSURANCE

CREATE TABLE MEDICAL_INSURANCE(
POLICY_ID INT PRIMARY KEY,
AGE INT,
GENDER VARCHAR(10),
BMI DECIMAL(5,2),
CHILDREN INT,
SMOKER VARCHAR(3),
REGION VARCHAR(20),
INSURANCE_COST DECIMAL(10,2))

SELECT * FROM MEDICAL_INSURANCE

INSERT INTO MEDICAL_INSURANCE VALUES (
1,19,'FEMALE',27.90,0,'YES','SOUTHWEST',16884.92),
(2,18,'MALE',33.77,1,'NO','SOUTHEAST',1725.55),
(3,28,'MALE',33.00,3,'NO','SOUTHEAST',4449.46),
(4, 33, 'Male', 22.70, 0, 'No', 'northwest', 21984.47),
(5, 32, 'Female', 28.88, 0, 'No', 'southeast', 3866.86),
(6, 31, 'Female', 25.74, 0, 'Yes', 'southeast', 3756.62),
(7, 46, 'Female', 33.44, 1, 'No', 'southeast', 8240.59),
(8, 37, 'Male', 27.74, 2, 'No', 'northwest', 7281.51),
(9, 37, 'Female', 29.83, 2, 'No', 'northeast', 6406.41),
(10, 60, 'Female', 25.84, 0, 'Yes', 'northwest', 28923.14);

UPDATE MEDICAL_INSURANCE
SET SMOKER=LOWER(SMOKER),REGION=LOWER(REGION)

SELECT COUNT(POLICY_ID) FROM MEDICAL_INSURANCE

SELECT * FROM MEDICAL_INSURANCE WHERE AGE>40 AND SMOKER="YES"

SELECT GENDER,COUNT(*) AS POLICYHOLDER_COUNT FROM MEDICAL_INSURANCE GROUP BY GENDER

SELECT SMOKER,AVG(INSURANCE_COST) AS AVGINSURANCE_COST 
FROM MEDICAL_INSURANCE
GROUP BY SMOKER

SELECT REGION,AVG(INSURANCE_COST) AS HIGHESTAVGINSURANCE_COST
FROM MEDICAL_INSURANCE
GROUP BY REGION 
ORDER BY HIGHESTAVGINSURANCE_COST DESC LIMIT 1

SELECT * FROM MEDICAL_INSURANCE
ORDER BY INSURANCE_COST DESC LIMIT 5

SELECT 
CASE 
WHEN AGE BETWEEN 18 AND 30 THEN 'YOUNG'
WHEN AGE BETWEEN 31 AND 50 THEN 'MIDDLE-AGED'
WHEN AGE >=51 THEN 'SENIOR'
END AS AGE_GROUP,
AVG(INSURANCE_COST) AS AVGINSURANCE_COST
FROM MEDICAL_INSURANCE M
GROUP BY AGE_GROUP

SELECT * FROM MEDICAL_INSURANCE


---FIND BMI>30 HIGHEST INSURANCE_COST PAYER

SELECT BMI,MAX(INSURANCE_COST) AS HIGHERINSURANCE
FROM MEDICAL_INSURANCE
WHERE BMI>30
GROUP BY BMI
ORDER BY MAX(INSURANCE_COST) DESC LIMIT 1

---Identify if smokers with BMI > 30 are paying significantly higher insurance than nonsmokers.

SELECT SMOKER,AVG(INSURANCE_COST) AS AVG_INSURANCE
FROM MEDICAL_INSURANCE
WHERE BMI>30
GROUP BY SMOKER

Find the correlation-like insights (not actual correlation in SQL, but using GROUP BY) –
e.g.,
o Avg cost by number of children.
o Avg cost by gender.
o Avg cost by region.

SELECT CHILDREN,AVG(INSURANCE_COST) AS AVG_INSURANCE
FROM MEDICAL_INSURANCE
GROUP BY CHILDREN
ORDER BY CHILDREN

SELECT GENDER,AVG(INSURANCE_COST) AS AVG_INSURANCE
FROM MEDICAL_INSURANCE
GROUP BY GENDER
ORDER BY GENDER

SELECT REGION,AVG(INSURANCE_COST) AS AVG_INSURANCE
FROM MEDICAL_INSURANCE
GROUP BY REGION
ORDER BY AVG_INSURANCE DESC

---Write a query to find the insurance cost difference between smokers and non-smokers
in each region----

SELECT
REGION,
AVG(CASE WHEN SMOKER='NO' THEN INSURANCE_COST END) AS AVGOFNONSMOKER,
AVG(CASE WHEN SMOKER='YES' THEN INSURANCE_COST END) AS AVGOFSMOKER,
(AVG(CASE WHEN SMOKER='NO' THEN INSURANCE_COST END)-AVG(CASE WHEN SMOKER='YES' THEN INSURANCE_COST END)) AS COST_DIFFERENCE
FROM MEDICAL_INSURANCE
GROUP BY REGION
ORDER BY COST_DIFFERENCE DESC







